
server:  port: 9000
  
eureka:  instance:    hostname: localhost

spring:
  application:
    name: Gateway
  cloud:    gateway:      routes:      - id: user
        uri: lb://user        predicates:        - Path=/users/**
      - id: Contacts
        uri: lb://Contacts
        predicates:
        - Path=/contacts/**
        